config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'static_pages#home'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [] do
    resources :questions, except: %i[index show]
    resources :votes, only: %i[create destroy]
    resources :answers, except: %i[index show]
  end

  resources :questions, only: %i[index show] do
    collection do
      get :search
      post :search
      get :my_questions
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include PgSearch
  paginates_per 20
  acts_as_paranoid
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable, dependent: :destroy

  validates :title, presence: true

  pg_search_scope :search_for, against: %i[title body], using: %i[tsearch trigram]

  def increment_score
    Question.increment_counter(:score, id)
  end

  def decrement_score
    Question.decrement_counter(:score, id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authorise_user, only: %i[edit update destroy]
  before_action :set_query, only: :search

  def index
    @questions = Question.all.order(score: :desc).includes(:answers, :user).page params[:page] if sorting_strategy.blank?
    @questions = Question.all.order(created_at: :desc).includes(:answers, :user).page params[:page] if sorting_strategy == 'recent'
  end

  def show; end

  def my_questions
    @questions = current_user.questions.order(score: :desc).includes(:answers, :user).page params[:page] if sorting_strategy.blank?
    @questions = current_user.questions.order(created_at: :desc).includes(:answers, :user).page params[:page] if sorting_strategy == 'recent'
  end

  def new
    @question = Question.new(user_id: current_user.id)
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Question submitted!'
      redirect_to @question
    else
      flash[:alert] = @question.errors.full_messages.join(", ")
      redirect_to new_user_question_path(current_user)
    end
  end

  def update
    if @question.update(question_params)
      flash[:notice] = 'Question saved!'
      redirect_to @question
    else
      flash[:alert] = @question.errors.full_messages.join(", ")
      redirect_to edit_user_question_path(@question)
    end
  end

  def destroy
    if @question.destroy
      flash[:notice] = 'Question successfully deleted!'
      redirect_to questions_path
    else
      flash[:alert] = @question.errors.full_messages.join(", ")
      redirect_to @question
    end
  end

  def search
    @questions = Question.search_for(@query).page params[:page]
  end

  def sorting_strategy
    @sorting_strategy ||= params[:sorting_strategy]
  end

  private

  def authorise_user
    if current_user.id != @question.user_id && !current_user.moderator_user
      flash[:alert] = 'You are not allowed to manipulate this resource'
      redirect_to questions_path and return
    end
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_query
    @query ||= params[:q]
  end

  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end
end

app/views/questions/_form.haml
= form_for [current_user, @question] do |f|
  = f.hidden_field :user_id
  .row
    .col-md-12
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
  .row
    .col-md-12
      .form-group
        = f.label :body
        = f.text_area :body, cols: "30", rows: "10", class: 'form-control'
  .row
    .col-md-12
      = f.submit 'Submit', class: 'btn btn-md btn-outline-success'

app/views/questions/_question.haml
- cache question do
  .row.form-group
    .col-md-9
      .row
        .col-md-12
          %h4
            =link_to question.title, question
      .row
        .col-md-12
          %em="#{ question.user.email } asked #{ distance_of_time_in_words(Time.now, question.created_at) } ago | #{ question.user.decorate.flair }| #{question.answers.count} answer(s) | #{question.score} point(s)".html_safe

app/views/questions/_question_collection.haml
.container
  .row
    .col-md-12
      - if @sorting_strategy
        %p= link_to 'Sort by most popular', questions_path, class: 'btn btn-outline-success'
      - else
        %p= link_to 'Sort by most recent', questions_path(sorting_strategy: 'recent'), class: 'btn btn-outline-secondary'
  = paginate @questions
  = render @questions
  = paginate @questions

app/views/questions/edit.haml
%h1
  Edit your question

= render 'form'

app/views/questions/index.haml
.container
  .row
    .col-md-12
      - if @sorting_strategy
        %p= link_to 'Sort by most popular', questions_path, class: 'btn btn-outline-success'
      - else
        %p= link_to 'Sort by most recent', questions_path(sorting_strategy: 'recent'), class: 'btn btn-outline-secondary'
  = paginate @questions
  = render @questions
  = paginate @questions

app/views/questions/my_questions.haml
= render 'question_collection'

app/views/questions/new.haml
%h1
  Ask a new question!

%h5.text-muted
  The QueryPad community values any enquiries from any of our employees

= render 'form'

app/views/questions/search.haml
%h1= "Search results for '#{@query}'"

%table
  %tbody
    = paginate @questions
    = render @questions
    = paginate @questions

app/views/questions/show.haml
.container
  #question
    .row
      .col-md-12
        %h1
          = @question.title
          %span.badge.badge-info
            = @question.score
    - if current_user.questions.include?(@question) || moderator_user
      %hr
      .row.form-group
        .col-md-5
          = link_to 'edit', edit_user_question_path(current_user, @question), class: 'btn btn-md btn-outline-info'
          = link_to 'delete', user_question_path(current_user, @question), method: :delete, class: 'btn btn-md btn-outline-danger'
    - unless current_user.questions.include?(@question)
      .row
        .col-md-12
          = render 'votes/votable', resource: @question, vote_cast: current_user.vote_cast(@question), question: @question
    .row
      .col-md-12
        %em= "#{ @question.user.email } #{ @question.user.decorate.flair } | #{ distance_of_time_in_words(Time.now, @question.created_at) } ago#{ @question.time_ago_if_edited }".html_safe
    .row
      .col-md-12
        = markdown(@question.body)
  #answers
    .row
      .col-md-12
        %h2
          Answers
    .row
      .col-md-12
        = link_to 'Add Answer', new_user_answer_path(current_user, question_id: @question)
      %hr
      .row
        .col-md-12
          = render @question.answers.order(score: :desc)