config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'static_pages#home'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [] do
    resources :questions, except: %i[index show]
    resources :votes, only: %i[create destroy]
    resources :answers, except: %i[index show]
  end

  resources :questions, only: %i[index show] do
    collection do
      get :search
      post :search
      get :my_questions
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  belongs_to :question, touch: true
  has_many :votes, as: :votable

  alias_attribute :answered_question, :question

  validates :body, presence: true

  def question_title
    question&.title
  end

  def increment_score
    Answer.increment_counter(:score, id)
  end

  def decrement_score
    Answer.decrement_counter(:score, id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :authorise_user, only: %i[edit update destroy]

  def show; end

  def new
    @answer = Answer.new(user_id: current_user.id, question_id: params[:question_id])
  end

  def edit; end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:notice] = 'Answer submitted!'
      redirect_to @answer.question
    else
      flash[:alert] = @answer.errors.full_messages.join(", ")
      redirect_to new_user_answer_path(current_user)
    end
  end

  def update
    if @answer.update(answer_params)
      flash[:notice] = 'Answer saved!'
      redirect_to @answer.question
    else
      flash[:alert] = @answer.errors.full_messages.join(", ")
      redirect_to edit_user_answer_path(@answer)
    end
  end

  def destroy
    if @answer.destroy
      flash[:notice] = 'Answer successfully deleted!'
      redirect_to questions_path
    else
      flash[:alert] = @answer.errors.full_messages.join(", ")
      redirect_to @answer.question
    end
  end

  private

  def authorise_user
    if current_user.id != @answer.user_id && !current_user.moderator_user
      flash[:alert] = 'You are not allowed to manipulate this resource'
      redirect_to questions_path and return
    end
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, :user_id)
  end
end

app/views/answers/_answer.haml
.row.form-group
  .col-md-12
    .row
      .col-md-12
        .bg-gray
          = markdown(answer.body)
    .row
      .col-md-12
        = "Score:"
        %span.badge.badge-primary
          = answer.score
    .row
      .col-md-12
        %em= "#{ answer.user.email } #{ answer.user.decorate.flair } | #{ distance_of_time_in_words(Time.now, answer.created_at) } ago#{ answer.time_ago_if_edited }".html_safe
  - if current_user.answers.include?(answer) || moderator_user
    .row
      .col-md-12
        = link_to 'edit answer', edit_user_answer_path(current_user, answer), class: 'btn btn-md btn-outline-info'
        = link_to 'delete answer', user_answer_path(current_user, answer), method: :delete, class: 'btn btn-md btn-outline-danger'
- unless current_user.answers.include?(answer)
  .row
    .col-md-12
      = render 'votes/votable', resource: answer, vote_cast: current_user.vote_cast(answer), question: @question
%hr

app/views/answers/_form.haml
= form_for [current_user, @answer] do |f|
  = f.hidden_field :question_id
  = f.hidden_field :user_id
  .row
    .col-md-12
      .form-group
        = f.label :body
        = f.text_area :body, cols: "30", rows: "10", class: 'form-control'
  .row
    .col-md-12
      = f.submit 'Submit', class: 'btn btn-md btn-outline-success'

app/views/answers/edit.haml
%h1= "Edit your answer for #{@answer.question_title}"

= render 'form'

app/views/answers/new.haml
.row
  .col-md-12
    %h3= "Submit your answer for '#{@answer&.question_title}'"
.container
  = render 'form'