config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'static_pages#home'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [] do
    resources :questions, except: %i[index show]
    resources :votes, only: %i[create destroy]
    resources :answers, except: %i[index show]
  end

  resources :questions, only: %i[index show] do
    collection do
      get :search
      post :search
      get :my_questions
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
  after_create :apply_vote_to_scores
  after_destroy :unapply_vote_to_scores

  private

  def apply_vote_to_scores
    if upvote?
      increment_scores
    else
      decrement_scores
    end
  end

  def unapply_vote_to_scores
    if upvote?
      decrement_scores
    else
      increment_scores
    end
  end

  def increment_scores
    votable.user.increment_score
    votable.increment_score
  end

  def decrement_scores
    votable.user.decrement_score
    votable.decrement_score
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :existing_votes, only: :create

  def create
    clear_opposite_votes
    if existing_votes.length > 0
      flash[:alert] = 'You have cancelled your vote'
      existing_votes.destroy_all
    else
      flash[:notice] = 'You have successfully voted!'
      @vote = Vote.create(vote_params)
    end
    redirect_to question_path(params[:vote][:question])
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def existing_votes
    @existing_votes ||= Vote.where(vote_params)
  end

  def vote_params
    params.require(:vote).permit(:upvote, :user_id, :votable_type, :votable_id)
  end

  def opposite_vote
    opposite = {'false': 'true', 'true': 'false'}[vote_params[:upvote].to_sym]
    @opposite_votes ||= Vote.where(vote_params.slice(:user_id, :votable_type, :votable_id).merge(upvote: opposite))
    @opposite_votes
  end

  def clear_opposite_votes
    opposite_vote.destroy_all if opposite_vote.exists?
  end
end

app/views/votes/_votable.haml
.row
  .col-md-12
    %h2{style: "color:grey;"}
      = link_to "#{vote_cast == 'Upvote' ? '👍' : '⬆️'}", user_votes_path(current_user, vote: { votable_type: resource.class, votable_id: resource.id, user_id: current_user.id, upvote: true, question: question.id }), method: :post
    - if power_user || moderator_user
      %h2
        = link_to "#{vote_cast == 'Downvote' ? '| 👎' : '| ⬇️'}", user_votes_path(current_user, vote: { votable_type: resource.class, votable_id: resource.id, user_id: current_user.id, upvote: false, question: question.id }), method: :post

app/views/votes/create.js.erb
console.log('oh shit does this work!')