config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'static_pages#home'

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [] do
    resources :questions, except: %i[index show]
    resources :votes, only: %i[create destroy]
    resources :answers, except: %i[index show]
  end

  resources :questions, only: %i[index show] do
    collection do
      get :search
      post :search
      get :my_questions
    end
  end
end

app/views/layouts/_flash_messages.haml
.container
  - flash.each do |type, msg|
    %div{:class => "alert #{bootstrap_class_for_flash(type)} alert-dismissable fade show"}
      = msg
      %button.close{"data-dismiss" => "alert"} x

app/views/layouts/_nav.haml
%nav.navbar.navbar-expand-md.navbar-light
  .navbar-brand
    %h2.text-muted
      QueryPad
  .collapse.navbar-collapse#navbarCollapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to 'Home', root_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Questions', questions_path, class: 'nav-link'
        %li.nav-item
          = link_to 'My Questions', my_questions_questions_path, class: 'nav-link'
        %li.nav-item
          = link_to 'New Question', new_user_question_path(current_user), class: 'nav-link'
        %li.nav-item
          = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = form_with url: search_questions_path, class: 'form-inline', local: true do |f|
            .form-group
              = f.search_field :q, class: 'form-control'
            .form-group
              = f.submit 'Search', class: 'form-control btn btn-success btn-md'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueryPad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <div class='header clearfix'>
        <%= render 'layouts/nav' %>
      </div>
      <!-- <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p> -->
      <%= render partial: 'layouts/flash_messages', flash: flash %>
      <br>
      <%= yield %>
    </div>
  </body>
</html>